const { db } = require('./database');
db.exec(`CREATE TABLE IF NOT EXISTS leads (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT,phone TEXT,company TEXT,linkedin TEXT,instagram TEXT,source TEXT DEFAULT 'manual',source_detail TEXT,status TEXT DEFAULT 'new' CHECK(status IN ('new','contacted','qualified','negotiating','active','closed_won','closed_lost','dead')),priority TEXT DEFAULT 'medium' CHECK(priority IN ('hot','high','medium','low','cold')),verification_score INTEGER DEFAULT 0,company_verified INTEGER DEFAULT 0,linkedin_verified INTEGER DEFAULT 0,pof_verified INTEGER DEFAULT 0,identity_verified INTEGER DEFAULT 0,deal_types TEXT,asset_types TEXT,price_range_min REAL,price_range_max REAL,markets TEXT,capital_available TEXT,pof_document TEXT,pof_status TEXT DEFAULT 'not_requested' CHECK(pof_status IN ('not_requested','requested','received','verified','rejected')),last_contact_date TEXT,next_followup_date TEXT,notes TEXT,created_at TEXT DEFAULT (datetime('now')),updated_at TEXT DEFAULT (datetime('now')))`);
db.exec(`CREATE TABLE IF NOT EXISTS lead_activities (id INTEGER PRIMARY KEY AUTOINCREMENT,lead_id INTEGER NOT NULL,type TEXT NOT NULL,title TEXT NOT NULL,description TEXT,metadata TEXT,created_at TEXT DEFAULT (datetime('now')),FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE)`);
db.exec(`CREATE TABLE IF NOT EXISTS verifications (id INTEGER PRIMARY KEY AUTOINCREMENT,lead_id INTEGER NOT NULL,type TEXT NOT NULL,status TEXT DEFAULT 'pending' CHECK(status IN ('pending','verified','failed','inconclusive')),result_data TEXT,source TEXT,verified_at TEXT,created_at TEXT DEFAULT (datetime('now')),FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE)`);
db.exec(`CREATE TABLE IF NOT EXISTS deal_pipeline (id INTEGER PRIMARY KEY AUTOINCREMENT,lead_id INTEGER NOT NULL,listing_id INTEGER,deal_name TEXT NOT NULL,deal_value REAL,fee_amount REAL,status TEXT DEFAULT 'prospect' CHECK(status IN ('prospect','intro_made','negotiating','under_contract','due_diligence','closing','closed','dead')),notes TEXT,created_at TEXT DEFAULT (datetime('now')),updated_at TEXT DEFAULT (datetime('now')),FOREIGN KEY (lead_id) REFERENCES leads(id))`);
const gary=db.prepare("SELECT id FROM leads WHERE company='Tru Vizions LLC'").get();
if(!gary){db.prepare("INSERT INTO leads (name,email,phone,company,source,source_detail,status,priority,deal_types,asset_types,price_range_min,price_range_max,markets,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run('Gary Randal','gary@truvizions.biz','562-269-5703','Tru Vizions LLC','website','First subscriber via subscribe page March 21 2026','new','high','real_estate','gas stations, multifamily, retail',5000000,300000000,'nationwide','First subscriber. 19 Crexi deals imported. Scores 80 on gas stations.');console.log('Gary Randal added as lead');}
const nik=db.prepare("SELECT id FROM leads WHERE instagram='nikolas_w_schlosser'").get();
if(!nik){db.prepare("INSERT INTO leads (name,instagram,source,source_detail,status,priority,deal_types,capital_available,notes) VALUES (?,?,?,?,?,?,?,?,?)").run('Nikolas W. Schlosser','nikolas_w_schlosser','instagram','Replied to DealMatcher comment - verified account','new','hot','real_estate','Has deals, asking about capital','Verified Instagram account. Has deal flow, wants to know about buyers.');console.log('Nikolas Schlosser added as HOT lead');}
console.log('Lead tables created. Total leads:', db.prepare("SELECT COUNT(*) as c FROM leads").get().c);
